--------------------------------------------------------
--  File created - Sunday-September-18-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADDRESS" 
   (	"ADDID" NUMBER(*,0), 
	"HOUSENO" VARCHAR2(20 BYTE), 
	"STREETNAME" VARCHAR2(20 BYTE), 
	"LOCALITY" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"PINCODE" NUMBER(*,0), 
	"COUNTRY" VARCHAR2(20 BYTE), 
	"EMPID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOYEE" 
   (	"EMPID" NUMBER(*,0), 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"MOBILE_NO" VARCHAR2(20 BYTE), 
	"FATHERNAME" VARCHAR2(20 BYTE), 
	"MOTHERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"DESIGNATION" VARCHAR2(20 BYTE), 
	"REPORTINGTO" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EDUCATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EDUCATION" 
   (	"EDUID" NUMBER(*,0), 
	"FIELDNAME" VARCHAR2(30 BYTE), 
	"SCHOOL" VARCHAR2(50 BYTE), 
	"UNIVERSITY" VARCHAR2(50 BYTE), 
	"GRADES" VARCHAR2(20 BYTE), 
	"EMPID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COUNTRY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."COUNTRY" 
   (	"COUNTRYID" NUMBER(*,0), 
	"COUNTRYNAME" VARCHAR2(50 BYTE), 
	"COUNTRYISDCODE" VARCHAR2(10 BYTE), 
	"COUNTRYCODETWO" VARCHAR2(10 BYTE), 
	"COUNTRYCODETHREE" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ADDRESS
SET DEFINE OFF;
Insert into SYSTEM.ADDRESS (ADDID,HOUSENO,STREETNAME,LOCALITY,CITY,STATE,PINCODE,COUNTRY,EMPID) values (22,'420','ZAMZAM','KHAJRANA','INDORE','Madhya Pradesh',450332,'INDIA',22);
Insert into SYSTEM.ADDRESS (ADDID,HOUSENO,STREETNAME,LOCALITY,CITY,STATE,PINCODE,COUNTRY,EMPID) values (15,'123','Mangal City Mall','Vijay Nagar','Indore','Madhya.Pradesh',452010,'India',15);
REM INSERTING into SYSTEM.EMPLOYEE
SET DEFINE OFF;
Insert into SYSTEM.EMPLOYEE (EMPID,FIRSTNAME,LASTNAME,USERNAME,EMAIL,MOBILE_NO,FATHERNAME,MOTHERNAME,PASSWORD,DESIGNATION,REPORTINGTO) values (22,'Mr','Shafeeque','shafique','Shafeeque@gmail.com','07400838375','mr Shiakh','Mrs Shaikh','12345678','Employee',null);
Insert into SYSTEM.EMPLOYEE (EMPID,FIRSTNAME,LASTNAME,USERNAME,EMAIL,MOBILE_NO,FATHERNAME,MOTHERNAME,PASSWORD,DESIGNATION,REPORTINGTO) values (15,'Danish','Qureshi','danish15','Danish.@velociters.com','1234568768','Father','Mother','12345678','Softwere Devloper',null);
REM INSERTING into SYSTEM.EDUCATION
SET DEFINE OFF;
Insert into SYSTEM.EDUCATION (EDUID,FIELDNAME,SCHOOL,UNIVERSITY,GRADES,EMPID) values (22,'Secondary',null,null,null,22);
Insert into SYSTEM.EDUCATION (EDUID,FIELDNAME,SCHOOL,UNIVERSITY,GRADES,EMPID) values (15,'Secondary','Gagngadhar','Hi ','Shaktimaan hai',15);
REM INSERTING into SYSTEM.COUNTRY
SET DEFINE OFF;
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (1,'Afghanistan','93','AF','AFG');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (2,'Albania','355','AL','ALB');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (3,'Algeria','213','DZ','DZA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (4,'American Samoa','1-684','AS','ASM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (5,'Andorra','376','AD','AND');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (6,'Angola','244','AO','AGO');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (7,'Anguilla','1-264','AI','AIA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (8,'Antarctica','672','AQ','ATA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (9,'Antigua and Barbuda','1-268','AG','ATG');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (10,'Argentina','54','AR','ARG');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (11,'Armenia','374','AM','ARM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (12,'Aruba','297','AW','ABW');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (13,'Australia','61','AU','AUS');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (14,'Austria','43','AT','AUT');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (15,'Azerbaijan','994','AZ','AZE');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (16,'Bahamas','1-242','BS','BHS');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (17,'Bahrain','973','BH','BHR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (18,'Bangladesh','880','BD','BGD');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (19,'Barbados','1-246','BB','BRB');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (20,'Belarus','375','BY','BLR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (21,'Belgium','32','BE','BEL');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (22,'Belize','501','BZ','BLZ');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (23,'Benin','229','BJ','BEN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (24,'Bermuda','1-441','BM','BMU');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (25,'Bhutan','975','BT','BTN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (26,'Bolivia','591','BO','BOL');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (27,'Bosnia and Herzegovina','387','BA','BIH');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (28,'Botswana','267','BW','BWA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (29,'Brazil','55','BR','BRA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (30,'British Indian Ocean Territory','246','IO','IOT');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (31,'British Virgin Islands','1-284','VG','VGB');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (32,'Brunei','673','BN','BRN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (33,'Bulgaria','359','BG','BGR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (34,'Burkina Faso','226','BF','BFA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (35,'Burundi','257','BI','BDI');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (36,'Cambodia','855','KH','KHM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (37,'Cameroon','237','CM','CMR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (38,'Canada','1','CA','CAN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (39,'Cape Verde','238','CV','CPV');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (40,'Cayman Islands','1-345','KY','CYM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (41,'Central African Republic','236','CF','CAF');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (42,'Chad','235','TD','TCD');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (43,'Chile','56','CL','CHL');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (44,'China','86','CN','CHN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (45,'Christmas Island','61','CX','CXR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (46,'Cocos Islands','61','CC','CCK');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (47,'Colombia','57','CO','COL');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (48,'Comoros','269','KM','COM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (49,'Cook Islands','682','CK','COK');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (50,'Costa Rica','506','CR','CRI');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (51,'Croatia','385','HR','HRV');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (52,'Cuba','53','CU','CUB');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (53,'Curacao','599','CW','CUW');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (54,'Cyprus','357','CY','CYP');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (55,'Czech Republic','420','CZ','CZE');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (56,'Democratic Republic of the Congo','243','CD','COD');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (57,'Denmark','45','DK','DNK');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (58,'Djibouti','253','DJ','DJI');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (59,'Dominica','1-767','DM','DMA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (60,'Dominican Republic','1-809 ','DO','DOM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (61,'East Timor','670','TL','TLS');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (62,'Ecuador','593','EC','ECU');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (63,'Egypt','20','EG','EGY');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (64,'El Salvador','503','SV','SLV');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (65,'Equatorial Guinea','240','GQ','GNQ');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (66,'Eritrea','291','ER','ERI');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (67,'Estonia','372','EE','EST');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (68,'Ethiopia','251','ET','ETH');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (69,'Falkland Islands','500','FK','FLK');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (70,'Faroe Islands','298','FO','FRO');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (71,'Fiji','679','FJ','FJI');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (72,'Finland','358','FI','FIN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (73,'France','33','FR','FRA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (74,'French Polynesia','689','PF','PYF');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (75,'Gabon','241','GA','GAB');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (76,'Gambia','220','GM','GMB');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (77,'Georgia','995','GE','GEO');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (78,'Germany','49','DE','DEU');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (79,'Ghana','233','GH','GHA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (80,'Gibraltar','350','GI','GIB');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (81,'Greece','30','GR','GRC');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (82,'Greenland','299','GL','GRL');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (83,'Grenada','1-473','GD','GRD');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (84,'Guam','1-671','GU','GUM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (85,'Guatemala','502','GT','GTM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (86,'Guernsey','44-1481','GG','GGY');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (87,'Guinea','224','GN','GIN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (88,'Guinea-Bissau','245','GW','GNB');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (89,'Guyana','592','GY','GUY');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (90,'Haiti','509','HT','HTI');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (91,'Honduras','504','HN','HND');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (92,'Hong Kong','852','HK','HKG');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (93,'Hungary','36','HU','HUN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (94,'Iceland','354','IS','ISL');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (95,'India','91','IN','IND');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (96,'Indonesia','62','ID','IDN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (97,'Iran','98','IR','IRN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (98,'Iraq','964','IQ','IRQ');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (99,'Ireland','353','IE','IRL');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (100,'Isle of Man','44-1624','IM','IMN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (101,'Israel','972','IL','ISR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (102,'Italy','39','IT','ITA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (103,'Ivory Coast','225','CI','CIV');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (104,'Jamaica','1-876','JM','JAM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (105,'Japan','81','JP','JPN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (106,'Jersey','44-1534','JE','JEY');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (107,'Jordan','962','JO','JOR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (108,'Kazakhstan','7','KZ','KAZ');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (109,'Kenya','254','KE','KEN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (110,'Kiribati','686','KI','KIR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (111,'Kosovo','383','XK','XKX');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (112,'Kuwait','965','KW','KWT');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (113,'Kyrgyzstan','996','KG','KGZ');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (114,'Laos','856','LA','LAO');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (115,'Latvia','371','LV','LVA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (116,'Lebanon','961','LB','LBN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (117,'Lesotho','266','LS','LSO');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (118,'Liberia','231','LR','LBR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (119,'Libya','218','LY','LBY');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (120,'Liechtenstein','423','LI','LIE');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (121,'Lithuania','370','LT','LTU');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (122,'Luxembourg','352','LU','LUX');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (123,'Macau','853','MO','MAC');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (124,'Macedonia','389','MK','MKD');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (125,'Madagascar','261','MG','MDG');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (126,'Malawi','265','MW','MWI');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (127,'Malaysia','60','MY','MYS');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (128,'Maldives','960','MV','MDV');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (129,'Mali','223','ML','MLI');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (130,'Malta','356','MT','MLT');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (131,'Marshall Islands','692','MH','MHL');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (132,'Mauritania','222','MR','MRT');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (133,'Mauritius','230','MU','MUS');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (134,'Mayotte','262','YT','MYT');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (135,'Mexico','52','MX','MEX');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (136,'Micronesia','691','FM','FSM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (137,'Moldova','373','MD','MDA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (138,'Monaco','377','MC','MCO');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (139,'Mongolia','976','MN','MNG');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (140,'Montenegro','382','ME','MNE');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (141,'Montserrat','1-664','MS','MSR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (142,'Morocco','212','MA','MAR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (143,'Mozambique','258','MZ','MOZ');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (144,'Myanmar','95','MM','MMR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (145,'Namibia','264','NA','NAM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (146,'Nauru','674','NR','NRU');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (147,'Nepal','977','NP','NPL');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (148,'Netherlands','31','NL','NLD');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (149,'Netherlands Antilles','599','AN','ANT');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (150,'New Caledonia','687','NC','NCL');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (151,'New Zealand','64','NZ','NZL');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (152,'Nicaragua','505','NI','NIC');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (153,'Niger','227','NE','NER');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (154,'Nigeria','234','NG','NGA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (155,'Niue','683','NU','NIU');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (156,'North Korea','850','KP','PRK');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (157,'Northern Mariana Islands','1-670','MP','MNP');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (158,'Norway','47','NO','NOR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (159,'Oman','968','OM','OMN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (160,'Pakistan','92','PK','PAK');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (161,'Palau','680','PW','PLW');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (162,'Palestine','970','PS','PSE');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (163,'Panama','507','PA','PAN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (164,'Papua New Guinea','675','PG','PNG');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (165,'Paraguay','595','PY','PRY');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (166,'Peru','51','PE','PER');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (167,'Philippines','63','PH','PHL');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (168,'Pitcairn','64','PN','PCN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (169,'Poland','48','PL','POL');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (170,'Portugal','351','PT','PRT');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (171,'Puerto Rico','1-787','PR','PRI');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (172,'Qatar','974','QA','QAT');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (173,'Republic of the Congo','242','CG','COG');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (174,'Reunion','262','RE','REU');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (175,'Romania','40','RO','ROU');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (176,'Russia','7','RU','RUS');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (177,'Rwanda','250','RW','RWA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (178,'Saint Barthelemy','590','BL','BLM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (179,'Saint Helena','290','SH','SHN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (180,'Saint Kitts and Nevis','1-869','KN','KNA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (181,'Saint Lucia','1-758','LC','LCA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (182,'Saint Martin','590','MF','MAF');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (183,'Saint Pierre and Miquelon','508','PM','SPM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (184,'Saint Vincent and the Grenadines','1-784','VC','VCT');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (185,'Samoa','685','WS','WSM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (186,'San Marino','378','SM','SMR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (187,'Sao Tome and Principe','239','ST','STP');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (188,'Saudi Arabia','966','SA','SAU');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (189,'Senegal','221','SN','SEN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (190,'Serbia','381','RS','SRB');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (191,'Seychelles','248','SC','SYC');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (192,'Sierra Leone','232','SL','SLE');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (193,'Singapore','65','SG','SGP');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (194,'Sint Maarten','1-721','SX','SXM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (195,'Slovakia','421','SK','SVK');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (196,'Slovenia','386','SI','SVN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (197,'Solomon Islands','677','SB','SLB');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (198,'Somalia','252','SO','SOM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (199,'South Africa','27','ZA','ZAF');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (200,'South Korea','82','KR','KOR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (201,'South Sudan','211','SS','SSD');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (202,'Spain','34','ES','ESP');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (203,'Sri Lanka','94','LK','LKA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (204,'Sudan','249','SD','SDN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (205,'Suriname','597','SR','SUR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (206,'Svalbard and Jan Mayen','47','SJ','SJM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (207,'Swaziland','268','SZ','SWZ');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (208,'Sweden','46','SE','SWE');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (209,'Switzerland','41','CH','CHE');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (210,'Syria','963','SY','SYR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (211,'Taiwan','886','TW','TWN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (212,'Tajikistan','992','TJ','TJK');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (213,'Tanzania','255','TZ','TZA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (214,'Thailand','66','TH','THA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (215,'Togo','228','TG','TGO');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (216,'Tokelau','690','TK','TKL');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (217,'Tonga','676','TO','TON');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (218,'Trinidad and Tobago','1-868','TT','TTO');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (219,'Tunisia','216','TN','TUN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (220,'Turkey','90','TR','TUR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (221,'Turkmenistan','993','TM','TKM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (222,'Turks and Caicos Islands','1-649','TC','TCA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (223,'Tuvalu','688','TV','TUV');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (224,'US  Virgin Islands','1-340','VI','VIR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (225,'Uganda','256','UG','UGA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (226,'Ukraine','380','UA','UKR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (227,'United Arab Emirates','971','AE','ARE');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (228,'United Kingdom','44','GB','GBR');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (229,'United States','1','US','USA');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (230,'Uruguay','598','UY','URY');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (231,'Uzbekistan','998','UZ','UZB');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (232,'Vanuatu','678','VU','VUT');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (233,'Vatican','379','VA','VAT');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (234,'Venezuela','58','VE','VEN');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (235,'Vietnam','84','VN','VNM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (236,'Wallis and Futuna','681','WF','WLF');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (237,'Western Sahara','212','EH','ESH');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (238,'Yemen','967','YE','YEM');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (239,'Zambia','260','ZM','ZMB');
Insert into SYSTEM.COUNTRY (COUNTRYID,COUNTRYNAME,COUNTRYISDCODE,COUNTRYCODETWO,COUNTRYCODETHREE) values (240,'Zimbabwe','263','ZW','ZWE');
--------------------------------------------------------
--  DDL for Index SYS_C007006
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007006" ON "SYSTEM"."EMPLOYEE" ("EMPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYEE" ADD PRIMARY KEY ("EMPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADDRESS" ADD FOREIGN KEY ("EMPID")
	  REFERENCES "SYSTEM"."EMPLOYEE" ("EMPID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EDUCATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EDUCATION" ADD FOREIGN KEY ("EMPID")
	  REFERENCES "SYSTEM"."EMPLOYEE" ("EMPID") ENABLE;
